title:            to days to come
description:      a blog for time travelling
url:              https://jiacheng.space
signoff:          jiacheng
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
github_username:  jiachengpan
share:            false # Turn on twitter and facebook share buttons
google_analytics: UA-45976965-3
disqus:           lovelyweasel

logo: assets/images/tardis_draw.png
bottom_logo: assets/images/scribble.png

collections:
  - notes

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
